# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'U-disk.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from numpy import double
import U_disk_convert

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 180)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_GBinput = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_GBinput.setGeometry(QtCore.QRect(51, 21, 232, 56))
        self.textEdit_GBinput.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.textEdit_GBinput.setObjectName("textEdit_GBinput")
        self.label_GB = QtWidgets.QLabel(self.centralwidget)
        self.label_GB.setGeometry(QtCore.QRect(290, 40, 37, 31))
        self.label_GB.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.label_GB.setObjectName("label_GB")
        self.textEdit_TBinput = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_TBinput.setGeometry(QtCore.QRect(51, 84, 232, 56))
        self.textEdit_TBinput.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.textEdit_TBinput.setObjectName("textEdit_TBinput")
        self.label_TB = QtWidgets.QLabel(self.centralwidget)
        self.label_TB.setGeometry(QtCore.QRect(290, 100, 34, 31))
        self.label_TB.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.label_TB.setObjectName("label_TB")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(334, 60, 93, 40))
        self.pushButton.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.pushButton.setObjectName("pushButton")
        self.textEdit_GBinput_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_GBinput_2.setGeometry(QtCore.QRect(434, 21, 521, 56))
        self.textEdit_GBinput_2.setStyleSheet(
            "font: 16pt \"Times New Roman\";")
        self.textEdit_GBinput_2.setObjectName("textEdit_GBinput_2")
        self.label_GB_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_GB_2.setGeometry(QtCore.QRect(970, 30, 37, 31))
        self.label_GB_2.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.label_GB_2.setObjectName("label_GB_2")
        self.textEdit_TBinput_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_TBinput_2.setGeometry(QtCore.QRect(434, 84, 521, 56))
        self.textEdit_TBinput_2.setStyleSheet(
            "font: 16pt \"Times New Roman\";")
        self.textEdit_TBinput_2.setObjectName("textEdit_TBinput_2")
        self.label_TB_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_TB_2.setGeometry(QtCore.QRect(970, 100, 34, 31))
        self.label_TB_2.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.label_TB_2.setObjectName("label_TB_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.convert)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def convert(self):
        if len(self.textEdit_GBinput.toPlainText()) == 0:
            self.textEdit_GBinput_2.setText('0')
        else:
            GB_in = self.textEdit_GBinput.toPlainText()
            temp1 = U_disk_convert.B2G(U_disk_convert.G2B(double(GB_in)))
            s1 = str(round(temp1*0.93, 4))+'~'+str(round(temp1, 4))
            self.textEdit_GBinput_2.setText(str(s1))
        if len(self.textEdit_TBinput.toPlainText()) == 0:
            self.textEdit_TBinput_2.setText('0')
        else:
            TB_in = self.textEdit_TBinput.toPlainText()
            temp2 = U_disk_convert.B2T(U_disk_convert.T2B(double(TB_in)))
            s2 = str(round(temp2*0.93, 4))+'~'+str(round(temp2, 4))
            self.textEdit_TBinput_2.setText(str(s2))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "U-disk-convert"))
        self.label_GB.setText(_translate("MainWindow", "GB"))
        self.label_TB.setText(_translate("MainWindow", "TB"))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        self.label_GB_2.setText(_translate("MainWindow", "GB"))
        self.label_TB_2.setText(_translate("MainWindow", "TB"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
