# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'U_disk.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(407, 393)
        MainWindow.setMinimumSize(QtCore.QSize(407, 393))
        MainWindow.setMaximumSize(QtCore.QSize(407, 393))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 130, 93, 40))
        self.pushButton.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.pushButton.setObjectName("pushButton")
        self.label_GB_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_GB_3.setGeometry(QtCore.QRect(110, 180, 189, 31))
        self.label_GB_3.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.label_GB_3.setObjectName("label_GB_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(60, 10, 302, 101))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textEdit_GBinput = QtWidgets.QTextEdit(self.widget)
        self.textEdit_GBinput.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.textEdit_GBinput.setObjectName("textEdit_GBinput")
        self.gridLayout_2.addWidget(self.textEdit_GBinput, 0, 0, 1, 1)
        self.label_GB = QtWidgets.QLabel(self.widget)
        self.label_GB.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.label_GB.setObjectName("label_GB")
        self.gridLayout_2.addWidget(self.label_GB, 0, 1, 1, 1)
        self.textEdit_TBinput = QtWidgets.QTextEdit(self.widget)
        self.textEdit_TBinput.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.textEdit_TBinput.setObjectName("textEdit_TBinput")
        self.gridLayout_2.addWidget(self.textEdit_TBinput, 1, 0, 1, 1)
        self.label_TB = QtWidgets.QLabel(self.widget)
        self.label_TB.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.label_TB.setObjectName("label_TB")
        self.gridLayout_2.addWidget(self.label_TB, 1, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(60, 230, 302, 101))
        self.widget1.setObjectName("widget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textEdit_GBinput_2 = QtWidgets.QTextEdit(self.widget1)
        self.textEdit_GBinput_2.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.textEdit_GBinput_2.setObjectName("textEdit_GBinput_2")
        self.gridLayout_3.addWidget(self.textEdit_GBinput_2, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_GB_2 = QtWidgets.QLabel(self.widget1)
        self.label_GB_2.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.label_GB_2.setObjectName("label_GB_2")
        self.gridLayout_3.addWidget(self.label_GB_2, 0, 1, 1, 1)
        self.textEdit_TBinput_2 = QtWidgets.QTextEdit(self.widget1)
        self.textEdit_TBinput_2.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.textEdit_TBinput_2.setObjectName("textEdit_TBinput_2")
        self.gridLayout_3.addWidget(self.textEdit_TBinput_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_TB_2 = QtWidgets.QLabel(self.widget1)
        self.label_TB_2.setStyleSheet("font: 16pt \"Times New Roman\";")
        self.label_TB_2.setObjectName("label_TB_2")
        self.gridLayout_3.addWidget(self.label_TB_2, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 407, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "U-disk-convert"))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        self.label_GB_3.setText(_translate("MainWindow", "以下范围为正常"))
        self.label_GB.setText(_translate("MainWindow", "GB"))
        self.label_TB.setText(_translate("MainWindow", "TB"))
        self.label_GB_2.setText(_translate("MainWindow", "GB"))
        self.label_TB_2.setText(_translate("MainWindow", "TB"))
